HasteBlockLocals = {
	["Ranged:"] = "Ranged:",
	["Mainhand:"] = "Mainhand:",
	["Offhand:"] = "Offhand:",
	["Spell:"] = "Spell:",
	["Show haste percentage"] = "Show haste percentage",
	["Show current attack speed"] = "Show current attack speed",
	["Show original attack speed"] = "Show original attack speed",
	["Show offhand attack speed"] = "Show offhand attack speed",
	["Show mainhand attack speed"] = "Show mainhand attack speed",
	["Show ranged attack speed"] = "Show ranged attack speed",
	["Show spell haste percentage"] = "Show spell haste percentage",
	["Always show block when no haste is active"] = "Always show block when no haste is active",
	["General"] = "General",
	["LegoBlock Settings"] = "LegoBlock Settings",
	["Hide Haste LegoBlock"] = "Hide Haste LegoBlock",
	["Show header text"] = "Show header text",
	["Scale: %d%%"] = "Scale: %d%%",
	["Background Opacity: %d%%"] = "Background Opacity: %d%%",
	["Border Opacity: %d%%"] = "Border Opacity: %d%%",
	["sec cast"] = "sec cast",
	
	-- For figuring out original cast time
	SPELLS = {
		["Wrath"] = 1.5,
		["Fireball"] = 1.5,
		["Holy Light"] = 2.5,
		["Lesser Heal"] = 1.5,
		["Immolate"] = 2.0,
		["Healing Wave"] = 1.5,
	},
}